# Configuration file for fraud detection project

data:
  raw_path: "data/raw/"
  processed_path: "data/processed/"

model:
  test_size: 0.33
  random_state: 42
  smote_strategy: 0.5
  threshold: 0.2
  cv_folds: 3

hyperparameter_tuning:
  n_iter: 10
  param_grid:
    classifier__n_estimators: [50, 100, 200]
    classifier__learning_rate: [0.01, 0.05, 0.1]
    classifier__max_depth: [3, 5, 7]
    classifier__num_leaves: [15, 31, 63]
    classifier__min_child_samples: [20, 50, 100]
    classifier__subsample: [0.8, 1.0]
    classifier__colsample_bytree: [0.8, 1.0]

paths:
  models: "models/saved_models/"
  results: "results/"
  figures: "results/figures/"
  submissions: "results/submissions/"